package com.shogiusa.shogiapi.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Entity representing the skill level of a Shogi player.
 * <p>
 * This entity categorizes players based on their skill level in Shogi. The levels typically
 * include kyu and dan ranks, from 15 kyu to 1 kyu, 1 dan, and up to 9 dan. These levels are crucial
 * for matching players of similar skill levels in tournaments and casual games.
 * <p>
 * The {@link Entity} annotation signifies that this class is a JPA entity, directly mapping
 * to the 'level' table in the database, as indicated by the {@link Table} annotation.
 * <p>
 * The {@link Data} annotation from Lombok automatically generates necessary Java code like
 * getters, setters, equals, hashCode, and toString methods, simplifying the class structure.
 */
@Data
@Entity
@Table(name = "player_shogi_level")
public class PlayerShogilLevel {

    /**
     * Unique identifier for the level.
     * <p>
     * This is the primary key in the 'level' table and is auto-generated by the database.
     * It uniquely identifies each level record.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the level.
     * <p>
     * This field represents the skill level's designation, such as '1 kyu', '1 dan', etc.
     * It is used to categorize players based on their proficiency in Shogi.
     */
    private String name;
}
